[package]
name = "emoticon-convert"
version = "0.1.0"
edition = "2021"

[dependencies]
client-extra = { path = "../../game/client-extra" }

image = { path = "../../lib/image" }

clap = { version = "4.5.23", features = ["derive"] }
tar = "0.4.43"
