[package]
name = "community"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../../lib/base" }

serde = { version = "1.0.217", features = ["derive"] }

ddnet-accounts-types = { version = "0.1.0" }
