[package]
name = "editor-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
editor = { path = "../../../game/editor" }
config = { path = "../../../lib/config" }
graphics = { path = "../../../lib/graphics" }
sound = { path = "../../../lib/sound" }
base-io = { path = "../../../lib/base-io" }
ui-base = { path = "../../../lib/ui-base" }
rayon = "1.10.0"
once_cell = "1.20.2"
egui = { version = "0.30.0", default-features = false, features = ["serde"] }

[lib]
crate-type = ["cdylib"]
