[package]
name = "egui-timeline"
version = "0.1.0"
edition = "2021"

[dependencies]
math = { path = "../../lib/math" }
map = { path = "../map" }
egui = { version = "0.30.0", default-features = false, features = ["serde"] }
egui_extras = { version = "0.30.0" }
