[package]
name = "community-register-server"
version = "0.1.0"
edition = "2021"

[dependencies]
community = { path = "../../game/community" }

tokio = { version = "1.42.0", features = ["rt-multi-thread", "sync", "fs", "net", "time", "macros"] }
anyhow = { version = "1.0.95", features = ["backtrace"] }
axum = "0.7.9"
clap = { version = "4.5.23", features = ["derive"] }

tower-http = { version = "0.6.2", features = ["fs", "trace"] }
