[package]
name = "community-server"
version = "0.1.0"
edition = "2021"

[dependencies]
community = { path = "../../game/community" }

base = { path = "../../lib/base" }
network = { path = "../../lib/network" }
sql = { path = "../../lib/sql" }
game-database = { path = "../../lib/game-database" }
game-database-backend = { path = "../../lib/game-database-backend" }

tokio = { version = "1.42.0", features = ["rt-multi-thread", "sync", "fs", "net", "time", "macros"] }
anyhow = { version = "1.0.95", features = ["backtrace"] }
clap = { version = "4.5.23", features = ["derive"] }
url = { version = "2.5.4", features = ["serde"] }
async-trait = "0.1.83"
reqwest = { version = "0.12.11", default-features = false, features = ["rustls-tls"] }
serde_json = "1.0.134"
x509-cert = { version = "0.2.5" }
log = "0.4.22"

ddnet-account-client-http-fs = { version = "0.2.0" }
ddnet-account-client-reqwest = "0.2.0"
ddnet-accounts-shared = { version = "0.2.0" }
ddnet-accounts-types = { version = "0.1.0" }
ddnet-account-game-server = { version = "0.3.0" }
